import { GameStateRequest } from "./types/GameStateRequest";
import { BackupProgress } from "../backups/types/BackupProgress";
import { BackupSummaryUpdate } from "../backups/types/BackupSummaryUpdate";
import { EBackupCreateResult } from "../backups/types/EBackupCreateResult";
import { EBackupDeleteResult } from "../backups/types/EBackupDeleteResult";
import { EBackupRestoreResult } from "../backups/types/EBackupRestoreResult";

import { EBackupRenameResult } from "../backups/types/EBackupRenameResult";
import { GithubRelease } from "../GithubRelease";
import { GameSaveSummaryUpdate } from "../GameSaveSummaryUpdate";
import { GameSaveActivityUpdate } from "../GameSaveActivityUpdate";
import { GameRuntimeState } from "../GameRuntimeState";
import { GameLaunchOptions } from "../launch/GameLaunchOptions";
import { CreateManualBackupOptions } from "../backups/types/CreateManualBackupOptions";
import { GameBundleState } from "../game-bundle/GameBundleState";
import { GameBundleInstallOptions } from "../game-bundle/GameBundleInstallOptions";
import { GameBundleDeleteOptions } from "../game-bundle/GameBundleDeleteOptions";
import { EGameBundleInstallResult } from "../game-bundle/EGameBundleInstallResult";
import { EGameBundleSetActiveResult } from "../game-bundle/EGameBundleSetActiveResult";
import { EGameBundleDeleteResult } from "../game-bundle/EGameBundleDeleteResult";
import { EGameLaunchResult } from "../launch/EGameLaunchResult";
import { EGameStopResult } from "../launch/EGameStopResult";
import { GameBundleInstallProgress } from "../game-bundle/GameBundleInstallProgress";
import { GameFileOperationState } from "../game-bundle/GameFileOperationState";
import { EGameFolderOpenResult } from "../EGameFolderOpenResult";

export type GameApi = {
    getState: (options?: GameStateRequest) => Promise<GameBundleState>;
    onStateChanged: (callback: (state: GameBundleState) => void) => () => void;
    getReleases: (forceRefresh?: boolean) => Promise<GithubRelease[]>;
    installLatestGameBundle: (options: GameBundleInstallOptions) => Promise<EGameBundleInstallResult>;
    cancelGameBundleDownload: () => Promise<boolean>;
    setActiveGameBundle: (gameBundleId: string) => Promise<EGameBundleSetActiveResult>;
    deleteGameBundle: (gameBundleId: string, options: GameBundleDeleteOptions) => Promise<EGameBundleDeleteResult>;
    getRuntimeState: () => Promise<GameRuntimeState>;
    launchActiveGameBundle: (options?: GameLaunchOptions) => Promise<EGameLaunchResult>;
    stop: () => Promise<EGameStopResult>;
    openGameBundleFolder: (gameBundleId: string) => Promise<EGameFolderOpenResult>;
    openSavesFolder: (gameBundleId: string) => Promise<EGameFolderOpenResult>;
    createManualBackup: (options?: CreateManualBackupOptions) => Promise<EBackupCreateResult>;
    restoreBackup: (backupId: string) => Promise<EBackupRestoreResult>;
    deleteBackup: (backupId: string) => Promise<EBackupDeleteResult>;
    renameBackup: (backupId: string, comment: string) => Promise<EBackupRenameResult>;
    getFileOperation: () => Promise<GameFileOperationState>;
    onFileOperationChanged: (callback: (operation: GameFileOperationState) => void) => () => void;
    onGameBundleInstallProgress: (callback: (progress: GameBundleInstallProgress) => void) => () => void;
    onRuntimeChanged: (callback: (runtime: GameRuntimeState) => void) => () => void;
    onSaveSummaryChanged: (callback: (update: GameSaveSummaryUpdate) => void) => () => void;
    onSaveActivityChanged: (callback: (update: GameSaveActivityUpdate) => void) => () => void;
    onBackupProgress: (callback: (progress: BackupProgress) => void) => () => void;
    onBackupSummaryChanged: (callback: (update: BackupSummaryUpdate) => void) => () => void;
};
